name: my_flutter_hello_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  provider: ^6.1.2
  convert: ^3.1.2
  async: ^2.12.0

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/mediaDB.json
    - assets/les_aventures_de_tintin.png
    - assets/asterix.png
    - assets/back_in_black.png
    - assets/fight_club.png
    - assets/gaston_lagaffe.png
    - assets/hybrid_theory.png
    - assets/la_quete_de_l_oignon_du_temps.png
    - assets/les_deux_tours.png
    - assets/oignonheimer.png
    - assets/rubrique_a_brac.png
    - assets/shrek_4.png
    - assets/shrek.png
    - assets/the_dark_side_of_the_moon.png
    - assets/the_hypnoflip_invasion.png
    - assets/thriller.png
    - assets/chernobyl.png
    - assets/les_cites_d_or.png
    - assets/sherlock.png
